"""add detail to runs_status_history

Revision ID: b25ed21abb6a
Revises: i9j0k1l2m3n4
Create Date: 2026-05-26 12:29:06.214450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25ed21abb6a'
down_revision: Union[str, None] = 'i9j0k1l2m3n4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_sequencer_uuid'), table_name='runs')
    op.drop_constraint(op.f('uq_runs_sequencer_name'), 'runs', type_='unique')
    op.add_column('runs_status_history', sa.Column('detail', sa.String(), nullable=True))
    op.drop_index(op.f('ix_sequencers_type_uuid'), table_name='sequencers')
    op.drop_index(op.f('uq_sequencers_name_active'), table_name='sequencers', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('uq_sequencers_slug_active'), table_name='sequencers', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_sequencertypes_id'), table_name='sequencers_types')
    op.drop_index(op.f('uq_sequencers_types_name_active'), table_name='sequencers_types', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_sequencers_types_id'), 'sequencers_types', ['id'], unique=False)
    op.create_index(op.f('ix_sequencers_types_name'), 'sequencers_types', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequencers_types_name'), table_name='sequencers_types')
    op.drop_index(op.f('ix_sequencers_types_id'), table_name='sequencers_types')
    op.create_index(op.f('uq_sequencers_types_name_active'), 'sequencers_types', ['name'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_sequencertypes_id'), 'sequencers_types', ['id'], unique=False)
    op.create_index(op.f('uq_sequencers_slug_active'), 'sequencers', ['slug'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('uq_sequencers_name_active'), 'sequencers', ['name'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_sequencers_type_uuid'), 'sequencers', ['type_uuid'], unique=False)
    op.drop_column('runs_status_history', 'detail')
    op.create_unique_constraint(op.f('uq_runs_sequencer_name'), 'runs', ['sequencer_uuid', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_runs_sequencer_uuid'), 'runs', ['sequencer_uuid'], unique=False)
    # ### end Alembic commands ###
